/**
 * Created by cshao on 2021-02-19.
 */

'use strict';

const ESSERIALIZER_NULL = '__ESSERIALIZER_NULL__';

const BOOLEAN_FIELD = 'ess_bool';
const CLASS_NAME_FIELD = 'ess_cn';
const TIMESTAMP_FIELD = 'ess_ts';
const TO_STRING_FIELD = 'ess_str';

const BUILTIN_CLASS_BOOLEAN = 'Boolean';
const BUILTIN_CLASS_DATE = 'Date';
const BUILTIN_CLASS_STRING = 'String';
const BUILTIN_CLASS_ERROR = 'Error';
const BUILTIN_CLASS_EVAL_ERROR = 'EvalError';
const BUILTIN_CLASS_RANGE_ERROR = 'RangeError';
const BUILTIN_CLASS_REFERENCE_ERROR = 'ReferenceError';
const BUILTIN_CLASS_SYNTAX_ERROR = 'SyntaxError';
const BUILTIN_CLASS_TYPE_ERROR = 'TypeError';
const BUILTIN_CLASS_URI_ERROR = 'URIError';
const BUILTIN_CLASS_AGGREGATE_ERROR = 'AggregateError';
const BUILTIN_TYPE_BIG_INT = 'BI';
const BUILTIN_TYPE_NOT_FINITE = 'NF';
const BUILTIN_TYPE_UNDEFINED = 'UD';

const ALL_BUILTIN_ERRORS = [
  BUILTIN_CLASS_ERROR,
  BUILTIN_CLASS_EVAL_ERROR,
  BUILTIN_CLASS_RANGE_ERROR,
  BUILTIN_CLASS_REFERENCE_ERROR,
  BUILTIN_CLASS_SYNTAX_ERROR,
  BUILTIN_CLASS_TYPE_ERROR,
  BUILTIN_CLASS_URI_ERROR,
  BUILTIN_CLASS_AGGREGATE_ERROR
];

export {
  ESSERIALIZER_NULL,
  ALL_BUILTIN_ERRORS,
  BUILTIN_CLASS_BOOLEAN,
  BUILTIN_CLASS_DATE,
  BUILTIN_CLASS_STRING,
  BUILTIN_CLASS_ERROR,
  BUILTIN_CLASS_EVAL_ERROR,
  BUILTIN_CLASS_RANGE_ERROR,
  BUILTIN_CLASS_REFERENCE_ERROR,
  BUILTIN_CLASS_SYNTAX_ERROR,
  BUILTIN_CLASS_TYPE_ERROR,
  BUILTIN_CLASS_URI_ERROR,
  BUILTIN_CLASS_AGGREGATE_ERROR,
  BUILTIN_TYPE_BIG_INT,
  BUILTIN_TYPE_NOT_FINITE,
  BUILTIN_TYPE_UNDEFINED,
  BOOLEAN_FIELD,
  CLASS_NAME_FIELD,
  TIMESTAMP_FIELD,
  TO_STRING_FIELD
};